name: 'snowflake_analytics_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_analytics_demo'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  snowflake_analytics_demo:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
    # Config indicated by + and applies to all files under models/marts/
    marts:
      +materialized: table

# Configuring tests
tests:
  snowflake_analytics_demo:
    +store_failures: true
